scape_format: latex

template_files:
  - template.tex

overridable_files:
  profile_picture: images/profile.jpg

default_settings:

intl:
  en:
    experience_header: Working Experience
    education_header: Education
    projects_header: Relevant Projects
    contacts_header: Contact
    languages_header: Languages
    skills_header: Skills
    socials_header: Online Presence
    more_portflio_text: 'See more from my portfolio:'
    more_publications_text: 'See all publications in:'
  es:
    experience_header: Experiencia Laboral
    education_header: Educación
    projects_header: Proyectos Relacionados
    contacts_header: Información de contacto
    languages_header: Idiomas
    skills_header: Habilidades
    socials_header: Perfiles Web
    more_portflio_text: 'Ver más proyectos en mi sitio web:'
    more_publications_text: 'Ver todas la publicaciones en:'
