scape_format: latex

template_files:
  - template.tex
  - deps/setup.tex

jinja_config:
  ".*\\.tex":
    block_start_string: '((*'
    block_end_string: '*))'
    variable_start_string: '((('
    variable_end_string: ')))'
    comment_start_string: '((='
    comment_end_string: '))'
    trim_blocks: true
    lstrip_blocks: true

overridable_files:
  profile_picture: images/profile.jpg

default_settings:
  background_color: 'FFFFFF'
  body_text_color: '333333'
  segment_title_color: 'E5680E'
  segment_subtitle_color: '999999'
  section_title_color: 'E5680E'
  section_title_line_color: 'E5680E'
  name_color: 'FFFFFF'
  last_name_color: 'FFFFFF'
  link_color: '555555'

intl:
  en:
    education_header: Education
    experience_header: Experience
    professional_subheader: Professional
    vocational_subheader: Vocational
    languages_header: Languages
    research_header: Research
    publications_subheader: Publications
    events_subheader: Events
    awards_subheader: Awards
    human_resource_training_header: Human Resource Training
    courses_taught_subheader: Courses taught
    supervised_students_subheader: Supervised students
  es:
    education_header: Educación
    experience_header: Experiencia
    professional_subheader: Profesional
    vocational_subheader: Vocacional
    languages_header: Idiomas
    research_header: Investigación
    publications_subheader: Publicaciones
    events_subheader: Eventos
    awards_subheader: Premios
    human_resource_training_header: Formación de Recursos Humanos
    courses_taught_subheader: Cursos Impartidos
    supervised_students_subheader: Estudiantes Supervisados
